/*
  Dual Photodiode True Random Number Generator (TRNG)

  - Uses two independent analog entropy sources (photodiodes)
  - Amplified using LM358 op-amp
  - Extracts least significant bit (LSB) from ADC readings
  - Applies Von Neumann whitening to remove bias
  - Converts the bits into bytes
  - Outputs unbiased random bytes over Serial
*/

int greenLED = 4;
int redLED = 5;
const int PIN1 = 34;
const int PIN2 = 35;
unsigned long lastLEDTime = 0;
const int ledDelay = 100; // 0.1 sec

// Pause/Resume button settings
const int BUTTON_PIN = 25;
bool running = true;
int buttonState;
int lastButtonState;
unsigned long lastDebounceTime = 0;

// Set to true to print readable output to Arduino Serial Monitor
// Set to false to output binary data for the Python Analyzer / Backend
bool debugMode = false;

uint32_t lfsr = 0xACE1u;

int getBit() {
  int rawBit = (analogRead(PIN1) ^ analogRead(PIN2)) & 1;
  delayMicroseconds(50); // Small delay
  
  // 32-bit Galois LFSR (taps 32, 22, 2, 1)
  unsigned lsb = lfsr & 1;
  lfsr >>= 1;
  if (lsb) {
    lfsr ^= 0x80200003;
  }
  
  // Whiten the raw bit by XORing with the LFSR bit
  return rawBit ^ lsb;
}

int getByte() {
  int value = 0;
  for(int i = 0; i < 8; i++){
    value = (value << 1) | getBit();
  }
  return value;
}

void setup() {
  Serial.begin(115200);

  pinMode(greenLED, OUTPUT);
  pinMode(redLED, OUTPUT);
  
  // Initialize push button with internal pull-up
  pinMode(BUTTON_PIN, INPUT_PULLUP);
  
  // Wait for the internal pull-up to charge the pin's capacitance
  delay(10);
  buttonState = digitalRead(BUTTON_PIN);
  lastButtonState = buttonState;
}

void loop(){

  // --- Button Edge Detection with 200ms Lockout ---
  int reading = digitalRead(BUTTON_PIN);
  
  if (debugMode) {
    static unsigned long lastDebugPrint = 0;
    if (millis() - lastDebugPrint > 500) {
      Serial.print("Raw Button Pin (GPIO 25): ");
      Serial.print(reading);
      Serial.print(" | State: ");
      Serial.println(running ? "RUNNING" : "PAUSED");
      lastDebugPrint = millis();
    }
  }

  if (reading == LOW && buttonState == HIGH && (millis() - lastDebounceTime > 200)) {
    running = !running;
    buttonState = LOW;
    lastDebounceTime = millis();
    if (debugMode) {
      Serial.println(">>> CLICK DETECTED! (Toggled state) <<<");
    }
  } 
  else if (reading == HIGH && buttonState == LOW && (millis() - lastDebounceTime > 200)) {
    buttonState = HIGH;
    lastDebounceTime = millis();
    if (debugMode) {
      Serial.println(">>> BUTTON RELEASED <<<");
    }
  }
  // Paused state behavior
  if (!running) {
    digitalWrite(greenLED, LOW);
    digitalWrite(redLED, LOW);
    return; // Exit early; loop() will immediately re-run to poll button
  }
  // --- End Button Logic ---

  // Raw analog readings (useful for debugging / analysis)
  //int val1 = analogRead(PIN1);
  //int val2 = analogRead(PIN2);

  // Extract final unbiased random byte via LFSR whitening
  int finalByte = getByte();

  // Output random bytes stream without blocking
  if (!debugMode) {
    // Binary output for analyzer/backend
    // Only write if there is space in the buffer to prevent the ESP32 from
    // freezing when the backend isn't actively reading the COM port!
    if (Serial.availableForWrite() >= 2) {
      Serial.write(0xAA); // sync marker
      Serial.write(finalByte);
    }
  }

  // LED visualization
  if(millis() - lastLEDTime >= ledDelay){ // Time for updation
    lastLEDTime = millis();

    int bit = finalByte & 1;  // Use the LSB of the generated byte

    if(bit == 1){
      digitalWrite(greenLED, HIGH);
      digitalWrite(redLED, LOW);
    } else {
      digitalWrite(greenLED, LOW);
      digitalWrite(redLED, HIGH);
    }
  }

  //Serial.println(b1);
  //Serial.println(val1);
  //Serial.println(finalByte);
}
