#pragma once

#include <vector>
#include <cstdint>
#include <mutex>
#include <condition_variable>
#include <thread>
#include <atomic>
#include <memory>
#include <chrono>

// Forward declaration
class IEntropySource;

/**
 * @brief Thread-safe entropy pool that maintains a buffer of random bytes
 * 
 * The EntropyPool runs a background thread that continuously collects entropy
 * from the active entropy source and stores it in a circular buffer.
 * 
 * Features:
 * - Background collection thread
 * - Thread-safe buffer access
 * - Blocking and non-blocking reads
 * - Configurable buffer size
 * - Automatic refill
 * - Graceful shutdown
 */
class EntropyPool {
public:
    /**
     * @brief Constructor
     * @param source Pointer to the entropy source to use
     * @param bufferSize Size of the internal buffer in bytes (default: 4096)
     * @param refillThreshold When buffer drops below this, trigger refill (default: 50%)
     */
    explicit EntropyPool(
        std::shared_ptr<IEntropySource> source,
        size_t bufferSize = 4096,
        size_t refillThreshold = 2048
    );

    /**
     * @brief Destructor - stops background thread
     */
    ~EntropyPool();

    /**
     * @brief Start the background collection thread
     * @return true if started successfully
     */
    bool start();

    /**
     * @brief Stop the background collection thread
     */
    void stop();

    /**
     * @brief Get entropy bytes from the pool (blocking)
     * 
     * Blocks until the requested number of bytes are available.
     * 
     * @param numBytes Number of bytes to read
     * @return std::vector<uint8_t> The entropy bytes
     * @throws EntropyException if pool is stopped or source unavailable
     */
    std::vector<uint8_t> getEntropy(size_t numBytes);

    /**
     * @brief Get a single byte from the pool (blocking)
     * @return uint8_t A random byte
     * @throws EntropyException if pool is stopped or source unavailable
     */
    uint8_t getByte();

    /**
     * @brief Try to get entropy bytes without blocking
     * 
     * @param numBytes Number of bytes requested
     * @param buffer Output buffer to fill
     * @return size_t Actual number of bytes read (may be less than requested)
     */
    size_t tryGetEntropy(size_t numBytes, std::vector<uint8_t>& buffer);

    /**
     * @brief Get the current number of bytes available in the pool
     * @return size_t Bytes available
     */
    size_t available() const;

    /**
     * @brief Get the total number of bytes generated by this pool
     * @return size_t Total bytes generated
     */
    size_t getTotalBytesGenerated() const;

    /**
     * @brief Check if the pool is running
     * @return true if running
     */
    bool isRunning() const;

    /**
     * @brief Check if the pool is empty
     * @return true if no bytes available
     */
    bool isEmpty() const;

    /**
     * @brief Check if the pool is full
     * @return true if buffer is full
     */
    bool isFull() const;

    /**
     * @brief Get the current buffer size
     * @return size_t Buffer size in bytes
     */
    size_t getBufferSize() const;

    /**
     * @brief Set the refill threshold
     * @param threshold Bytes remaining to trigger refill
     */
    void setRefillThreshold(size_t threshold);

    /**
     * @brief Get the refill threshold
     * @return size_t Refill threshold in bytes
     */
    size_t getRefillThreshold() const;

    /**
     * @brief Force an immediate refill of the pool
     * @return true if refill was successful
     */
    bool refill();

    /**
     * @brief Set the entropy source
     * @param source New entropy source
     */
    void setSource(std::shared_ptr<IEntropySource> source);

    /**
     * @brief Get the current entropy source name
     * @return std::string Source name
     */
    std::string getSourceName() const;

private:
    /**
     * @brief Background thread function that continuously collects entropy
     */
    void collectionThread();

    /**
     * @brief Collect entropy from the source and add to buffer
     * @return true if collection was successful
     */
    bool collectEntropy();

    /**
     * @brief Add bytes to the buffer (internal, assumes lock held)
     * @param data Bytes to add
     */
    void addBytes(const std::vector<uint8_t>& data);

    /**
     * @brief Read bytes from the buffer (internal, assumes lock held)
     * @param numBytes Number of bytes to read
     * @return std::vector<uint8_t> The bytes read
     */
    std::vector<uint8_t> readBytes(size_t numBytes);

    /**
     * @brief Check if refill is needed
     * @return true if buffer is below threshold
     */
    bool needsRefill() const;

    // Entropy source
    std::shared_ptr<IEntropySource> entropySource;

    // Buffer
    std::vector<uint8_t> buffer;
    size_t head;  // Read position
    size_t tail;  // Write position
    size_t count; // Number of bytes available

    // Buffer configuration
    size_t bufferSize;
    size_t refillThreshold;

    // State
    std::atomic<bool> running;
    std::atomic<bool> stopped;
    std::atomic<size_t> totalBytesGenerated;

    // Synchronization
    mutable std::mutex mutex;
    std::condition_variable cv;
    std::condition_variable refillCV;

    // Background thread
    std::thread collectorThread;

    // Collection settings
    static constexpr size_t COLLECTION_BATCH_SIZE = 64;  // Bytes per batch
    static constexpr std::chrono::milliseconds COLLECTION_INTERVAL{10}; // 10ms
};