#pragma once

#include <vector>
#include <cstdint>
#include <string>
#include <stdexcept>

/**
 * @brief Interface for entropy sources
 * 
 * All entropy providers must implement this interface.
 * This allows the system to swap between hardware (ESP32)
 * and software (OpenSSL) entropy sources seamlessly.
 * 
 * The "I" prefix stands for "Interface" - a common C++ convention
 * for abstract base classes.
 */
class IEntropySource {
public:
    /**
     * @brief Virtual destructor for proper cleanup of derived classes
     */
    virtual ~IEntropySource() = default;

    /**
     * @brief Get entropy bytes from the source
     * 
     * @param numBytes Number of random bytes to generate
     * @return std::vector<uint8_t> Vector containing the entropy bytes
     * 
     * @throws std::runtime_error if entropy generation fails
     */
    virtual std::vector<uint8_t> getEntropy(size_t numBytes) = 0;

    /**
     * @brief Get a single byte of entropy
     * 
     * @return uint8_t A random byte
     * 
     * @throws std::runtime_error if entropy generation fails
     */
    virtual uint8_t getByte() = 0;

    /**
     * @brief Check if the entropy source is available and working
     * 
     * @return true if source is available and operational
     * @return false if source is unavailable or failed
     */
    virtual bool isAvailable() const = 0;

    /**
     * @brief Get a human-readable name for this entropy source
     * 
     * @return std::string Source name (e.g., "ESP32 Hardware", "OpenSSL")
     */
    virtual std::string getSourceName() const = 0;

    /**
     * @brief Get the source type identifier
     * 
     * @return std::string Type identifier (e.g., "hardware", "openssl")
     */
    virtual std::string getSourceType() const = 0;

    /**
     * @brief Initialize the entropy source
     * 
     * Some sources may need setup (e.g., opening serial port).
     * 
     * @return true if initialization succeeded
     * @return false if initialization failed
     */
    virtual bool initialize() = 0;

    /**
     * @brief Shutdown/cleanup the entropy source
     * 
     * Close connections, free resources, etc.
     */
    virtual void shutdown() = 0;

    /**
     * @brief Get the total number of bytes generated by this source
     * 
     * @return size_t Total bytes generated since initialization
     */
    virtual size_t getTotalBytesGenerated() const = 0;

    /**
     * @brief Reset the byte counter
     */
    virtual void resetByteCounter() = 0;

    /**
     * @brief Check if the source supports reseeding
     * 
     * @return true if source can be reseeded
     * @return false if source doesn't support reseeding
     */
    virtual bool supportsReseeding() const = 0;

    /**
     * @brief Reseed the entropy source (if supported)
     * 
     * @throws std::runtime_error if reseeding is not supported or fails
     */
    virtual void reseed() = 0;
};

/**
 * @brief Helper exception for entropy-related errors
 */
class EntropyException : public std::runtime_error {
public:
    explicit EntropyException(const std::string& msg) 
        : std::runtime_error("Entropy Error: " + msg) {}
};